### PR TITLE
Write support for optional schema documentation fields

### PR DESCRIPTION
**Pull request by jjohs**
- nullable
- readOnly
- writeOnly
- externalDocs
- example
- deprecated

### CODE REVIEW

**Comment by jjohs** [comment]
@darrelmiller any chance you can publish v0.8.7 to nuget that includes this final commit?  This is a stop gap until OpenAPI.NET is out of beta / stable, and we are able re-integrate against the new library.  Thanks

**Comment by darrelmiller** [comment]
@jjohs Will do.

**Comment by darrelmiller** [comment]
@jjohs Done

**Comment by jjohs** [comment]
Thanks @darrelmiller.  Will see you on the OpenAPI.NET side...

**Pull request merged**
