### PR TITLE
Extensions write support

### LINKED ISSUE #4: Implement support for parsing and validating extensions

### PR DESCRIPTION
**Pull request by jjohs**
- implemented AnyNode write support for ValueNode and ListNode (scalars types)
- v2 and v3 write support for extensions

fixes #4 (partial support - MapNode write not implemented)

### CODE REVIEW

**Comment by jjohs** [comment]
@darrelmiller let me know if you have questions/concerns with the approach, or required changes in order to merge.  Thanks

**Comment by darrelmiller** [comment]
Hey @jjohs Thanks for the PR.  Sorry for going dark.  This project has found a new home, with a bunch of extra hands to support it.  I've also done a bunch of refactoring to separate the model & writers from the reader.  Just working through a bunch of legal crap and then I'll point to the new repo.  Will still be OSS but with MIT license instead and a different name.

**Comment by darrelmiller** [comment]
I can still merge these changes and publish a new release of Tavis.OpenAPI in the meanwhile if that would help?

**Comment by jjohs** [comment]
@darrelmiller if you could merge/publish, I would appreciate it.  We will then cut-over when the new project is available.  Thanks.

**Comment by darrelmiller** [comment]
@jjohs  Version 0.8.5 should be available shortly

**Comment by jjohs** [comment]
@darrelmiller thanks for pushing this through!

**Pull request merged**
